### ISSUE TITLE
How we can add new languages like Yaml or HCL(terraform)  

### ISSUE THREAD

**Issue by babakDoraniArab** [The-Pcode/pcode#5]
Hello 
Thank you so much for this repo. I love it, and I wondered how we could add HCL or YAML to this repo. I love to contribute to this language. But it depends on your decision? if you are interested too, we can have a meeting for that and talk more about adding  new languages 

Br
Babak

**Comment by aliturkamanjs** [comment]
hi babak thank you
we used the codemirror library to beautify the code
these languages ​​that you say should be supported by this library so that we can add

you can check this link  https://uiwjs.github.io/react-codemirror/
